export const LOADER = 'LOADER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

export const FEED_RESPONSE = 'FEED_RESPONSE';
export const FEED_REQUEST = 'FEED_REQUEST';

export const POST_RESPONSE = 'POST_RESPONSE';
export const POST_REQUEST = 'POST_REQUEST';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_RESPONSE = 'POST_COMMENT_RESPONSE';
